spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/motus_player}
    username: ${SPRING_DATASOURCE_USERNAME:motus}
    password: ${SPRING_DATASOURCE_PASSWORD:motus}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

motus:
  admin:
    password: "0000"
